### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by riceball1** [riceball1/simple-code#20]
TODO LIST
----------

```
Created On: March 31, 2017
Last Modified: May 9, 2017
````

This is a todo list created after already setting up a node/express/mongodb api, and creating a react/redux application with login/signup using jwt 

## Mentor Suggested Fixes
- [x] Fix all requests to API to send Authorization header
- [x] Add RequireAuth to dashboard in react-router.
    - Resource: http://www.thegreatcodeadventure.com/jwt-authentication-with-react-redux/
    - Solution (not 100% safe?) form the requireAuth here: http://www.thegreatcodeadventure.com/jwt-authentication-with-react-redux/
- [x] Make readme for project. 
- [x] Add demo account

## Signup
- [ ] Make sure that username and email are unique before user can create account

## Deleting Issues
- [x] Deleting text in the input fields - results in blank text (e.g., no titles)
- [x] Deleting all snippets - should result in a new page rendered to replace space
- [x] Deleting an array with 3 items results in the 2nd item to remain on the screen, and not move to the next array item

## Authentication

- [ ] fix authentication for routes and api (to make 100% full proof)

## Snippets

- [x] snippet should populate with data when selecting on a specific snippet

- [x] replace snippet textarea with codemirror

- [x] snippets should be only those of current user (fix in API)

- [x] debug issue with deleting 

- [x]  Fix issue with editing a snippet 
    - Resource on editing: http://www.thegreatcodeadventure.com/react-redux-tutorial-part-vi-the-edit-feature/

## Notifications

- [ ] Create flash messages whenever user completes tasks (e.g., saved snippet, signed in, logged in, deleted snippet, updated snippet)
    - Update: Only add flash messages for login/signup and errors

## Search

- [x] Create GET request to retreive specific snippets
    - Note: Where will the search result show? Does it replace the snippets that are already in the sidebar?
    - Update: Typing in a search should narrow items in sidebar
    - Resource: https://medium.com/@yaoxiao1222/implementing-search-filter-a-list-on-redux-react-bb5de8d0a3ad

## Landing Page

- [x] Add content to describe how the app works, why it was built, etc.

## Sidebar

- [x] Sidebar button can be animated to make (UI/UX addition)

- [ ] Add handler for 'Settings' - can be popup modal

- [x] Improve style of individual snippet previews

## Testing

- [ ] Add enzyme testing
    - Resource: https://semaphoreci.com/community/tutorials/testing-react-components-with-enzyme-and-mocha
    - React unit testing: https://medium.freecodecamp.com/react-unit-testing-with-mocha-and-enzyme-77d18b6875cb
